"""
Static string translations for report rendering (English / French).

Only report labels live here — Finding.title and vuln_class rationale text
are generated once at probe time in English and are not re-translated.
"""

from __future__ import annotations

_STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "report_title":        "WASP Scan Report",
        "network_report_title":"WASP Network Scan Report",
        "target":              "Target",
        "target_range":        "Target range",
        "date":                "Date",
        "duration":             "Duration",
        "model":               "Model",
        "tester_rig":          "Tester rig",
        "tester_tools":        "Tool versions",
        "findings":            "Findings",
        "hosts_scanned":       "Hosts scanned",
        "total_findings":      "Total findings",
        "no_findings":         "No confirmed vulnerabilities found in this scan.",
        "no_findings_network": "No confirmed vulnerabilities found across the network.",
        "no_findings_note":    "This does not mean the target is secure. WASP tests a subset "
                                "of vulnerability classes with a single probe per class. "
                                "Manual testing is always recommended.",
        "summary":             "Summary",
        "host_summary":        "Host Summary",
        "all_findings":        "All Findings",
        "col_severity":        "Severity",
        "col_cvss":            "CVSS",
        "col_title":           "Title",
        "col_url":             "URL",
        "col_mitre":           "MITRE ATT&CK",
        "col_host":            "Host",
        "col_type":            "Type",
        "col_ports":           "Ports",
        "col_cve":             "CVE",
        "findings_section":    "Findings",
        "class_label":         "Class",
        "discovered":          "Discovered",
        "tactic":              "Tactic",
        "description":         "Description",
        "remediation":         "Remediation",
        "recommended_delay":   "Recommended timeline",
        "artifact":            "Artifact",
        "artifact_bloodhound_note": "import into BloodHound GUI (Neo4j) for attack-path graph analysis; treat as sensitive and destroy after review.",
        "delay_immediate":     "Immediate",
        "delay_30":            "30 days",
        "delay_90":            "90 days",
        "request":             "Request",
        "evidence":            "Evidence (click to expand)",
        "disclaimer":          "Disclaimer",
        "disclaimer_text":     "This report was generated by WASP — Web Application Security "
                                "Probe. Findings are produced by a local LLM and should be "
                                "manually verified before acting on them. Only use this tool "
                                "against systems you own or are explicitly authorized to test.",
        "disclaimer_network":  "Generated by WASP. Only use against networks you own or are "
                                "explicitly authorised to test. Findings require manual "
                                "verification.",
        "credential_attestation_title": "Credential Handling Attestation",
        "credential_attestation_text":  "Any credentials, hashes, or tickets captured during "
                                "this engagement (e.g. via null-bind enumeration, Kerberoasting, "
                                "or AS-REP Roasting) were used solely to confirm the findings "
                                "above and have been permanently destroyed from the tester's "
                                "environment. None were retained, exported, or shared beyond "
                                "this report.",
        # Executive report
        "exec_title":          "WASP Executive Summary",
        "exec_scope":          "Scope",
        "exec_overview":       "Overview",
        "exec_risk_rating":    "Overall Risk Rating",
        "exec_severity_breakdown": "Findings by Severity",
        "exec_top_risks":      "Top Risks",
        "exec_recommendations":"Recommendations",
        "exec_business_impact":"Business Impact",
        "exec_disclaimer_text":"This assessment reflects automated, point-in-time testing. "
                                "It should be complemented with professional manual review "
                                "before being used as the sole basis for risk decisions.",
        "risk_critical":       "CRITICAL — immediate action required",
        "risk_high":           "HIGH — action required soon",
        "risk_medium":         "MEDIUM — should be addressed",
        "risk_low":            "LOW — minor hardening opportunity",
        "risk_none":           "NO CONFIRMED FINDINGS",
        "no_top_risks":        "No confirmed findings — no action required at this time.",
    },
    "fr": {
        "report_title":        "Rapport de scan WASP",
        "network_report_title":"Rapport de scan réseau WASP",
        "target":              "Cible",
        "target_range":        "Plage cible",
        "date":                "Date",
        "duration":             "Durée",
        "model":               "Modèle",
        "tester_rig":          "Poste testeur",
        "tester_tools":        "Versions des outils",
        "findings":            "Vulnérabilités",
        "hosts_scanned":       "Hôtes scannés",
        "total_findings":      "Total des vulnérabilités",
        "no_findings":         "Aucune vulnérabilité confirmée lors de ce scan.",
        "no_findings_network": "Aucune vulnérabilité confirmée sur l'ensemble du réseau.",
        "no_findings_note":    "Cela ne signifie pas que la cible est sécurisée. WASP teste "
                                "un sous-ensemble de classes de vulnérabilités avec un seul "
                                "test par classe. Des tests manuels sont toujours recommandés.",
        "summary":             "Résumé",
        "host_summary":        "Résumé par hôte",
        "all_findings":        "Toutes les vulnérabilités",
        "col_severity":        "Sévérité",
        "col_cvss":            "CVSS",
        "col_title":           "Titre",
        "col_url":             "URL",
        "col_mitre":           "MITRE ATT&CK",
        "col_host":            "Hôte",
        "col_type":            "Type",
        "col_ports":           "Ports",
        "col_cve":             "CVE",
        "findings_section":    "Vulnérabilités",
        "class_label":         "Classe",
        "discovered":          "Découvert",
        "tactic":              "Tactique",
        "description":         "Description",
        "remediation":         "Remédiation",
        "recommended_delay":   "Délai recommandé",
        "artifact":            "Artefact",
        "artifact_bloodhound_note": "à importer dans BloodHound GUI (Neo4j) pour analyse graphique des chemins d'attaque ; à traiter comme sensible et détruire après analyse.",
        "delay_immediate":     "Immédiat",
        "delay_30":            "30 jours",
        "delay_90":            "90 jours",
        "request":             "Requête",
        "evidence":            "Preuve (cliquer pour développer)",
        "disclaimer":          "Avertissement",
        "disclaimer_text":     "Ce rapport a été généré par WASP — Web Application Security "
                                "Probe. Les vulnérabilités sont produites par un modèle de "
                                "langage local et doivent être vérifiées manuellement avant "
                                "toute action. N'utilisez cet outil que sur des systèmes que "
                                "vous possédez ou que vous êtes explicitement autorisé à tester.",
        "disclaimer_network":  "Généré par WASP. À utiliser uniquement sur des réseaux que "
                                "vous possédez ou que vous êtes explicitement autorisé à "
                                "tester. Les vulnérabilités nécessitent une vérification "
                                "manuelle.",
        "credential_attestation_title": "Attestation de traitement des identifiants",
        "credential_attestation_text":  "Tout identifiant, hash ou ticket capturé durant cette "
                                "mission (via énumération en bind anonyme, Kerberoasting ou "
                                "AS-REP Roasting) n'a servi qu'à confirmer les vulnérabilités "
                                "ci-dessus et a été détruit de façon permanente de "
                                "l'environnement du testeur. Aucun n'a été conservé, exporté "
                                "ou partagé au-delà de ce rapport.",
        # Executive report
        "exec_title":          "Synthèse exécutive WASP",
        "exec_scope":          "Périmètre",
        "exec_overview":       "Vue d'ensemble",
        "exec_risk_rating":    "Niveau de risque global",
        "exec_severity_breakdown": "Vulnérabilités par sévérité",
        "exec_top_risks":      "Principaux risques",
        "exec_recommendations":"Recommandations",
        "exec_business_impact":"Impact métier",
        "exec_disclaimer_text":"Cette évaluation reflète un test automatisé, à un instant "
                                "donné. Elle doit être complétée par une revue manuelle "
                                "professionnelle avant de servir de seule base à des "
                                "décisions de risque.",
        "risk_critical":       "CRITIQUE — action immédiate requise",
        "risk_high":           "ÉLEVÉ — action requise rapidement",
        "risk_medium":         "MOYEN — à corriger",
        "risk_low":            "FAIBLE — opportunité de durcissement mineure",
        "risk_none":           "AUCUNE VULNÉRABILITÉ CONFIRMÉE",
        "no_top_risks":        "Aucune vulnérabilité confirmée — aucune action requise pour le moment.",
    },
}


def t(key: str, lang: str = "en") -> str:
    """Look up a translated string, falling back to English then the key itself."""
    return _STRINGS.get(lang, _STRINGS["en"]).get(key, _STRINGS["en"].get(key, key))


def _self_check():
    assert t("summary", "en") == "Summary"
    assert t("summary", "fr") == "Résumé"
    assert t("summary", "de") == "Summary"          # unknown lang falls back to English
    assert t("nonexistent_key", "fr") == "nonexistent_key"


if __name__ == "__main__":
    _self_check()
    print("ok")
